version: 0.1
log:
  fields:
    service: registry
    environment: staging
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /blobs
  maintenance:
    uploadpurging:
      enabled: false
http:
  addr: :5000
  relativeurls: true
  headers:
    X-Content-Type-Options: [nosniff]